// data.js

// Ngày trong tháng
export const days = [...Array(31).keys()].map((d) => d + 1); // Ngày từ 1 đến 31

// Các tháng trong năm
export const months = [
  "Tháng 1",
  "Tháng 2",
  "Tháng 3",
  "Tháng 4",
  "Tháng 5",
  "Tháng 6",
  "Tháng 7",
  "Tháng 8",
  "Tháng 9",
  "Tháng 10",
  "Tháng 11",
  "Tháng 12",
];

// Các năm từ 2025 đến 1925
export const years = [...Array(100).keys()].map((y) => 2025 - y);

// Các tỉnh/thành phố lớn ở Việt Nam
export const cities = [
  "Hà Nội",
  "TP. Hồ Chí Minh",
  "Đà Nẵng",
  "Hải Phòng",
  "Cần Thơ",
  "Hải Dương",
  "Bình Dương",
  "Long An",
  "Bà Rịa - Vũng Tàu",
  "Khánh Hòa",
  "Thừa Thiên Huế",
  "Quảng Ninh",
  "Bắc Ninh",
  "Bình Thuận",
  "Lâm Đồng",
  "Ninh Bình",
  "Nam Định",
  "Vĩnh Phúc",
  "Tây Ninh",
  "Sóc Trăng",
  "Bình Phước",
  "Phú Thọ",
  "Bình Định",
];

// Các quận/huyện của Hà Nội và TP.Hồ Chí Minh (dữ liệu mẫu)
export const districts = {
  "Hà Nội": [
    "Quận Ba Đình",
    "Quận Hoàn Kiếm",
    "Quận Hai Bà Trưng",
    "Quận Tây Hồ",
    "Quận Cầu Giấy",
    "Quận Đống Đa",
    "Quận Hoàng Mai",
    "Quận Thanh Xuân",
    "Quận Long Biên",
    "Quận Nam Từ Liêm",
    "Quận Bắc Từ Liêm",
    "Huyện Ba Vì",
    "Huyện Chương Mỹ",
    "Huyện Gia Lâm",
    "Huyện Mê Linh",
    "Huyện Mỹ Đức",
    "Huyện Phú Xuyên",
  ],
  "TP. Hồ Chí Minh": [
    "Quận 1",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Quận Bình Thạnh",
    "Quận Tân Bình",
    "Quận Tân Phú",
    "Quận Phú Nhuận",
    "Quận Gò Vấp",
    "Quận 12",
    "Quận Thủ Đức",
    "Quận Bình Tân",
    "Huyện Bình Chánh",
    "Huyện Cần Giờ",
    "Huyện Củ Chi",
    "Huyện Hóc Môn",
  ],
  "Đà Nẵng": [
    "Quận Hải Châu",
    "Quận Thanh Khê",
    "Quận Liên Chiểu",
    "Quận Sơn Trà",
    "Quận Ngũ Hành Sơn",
    "Huyện Hoà Vang",
  ],
  "Hải Phòng": [
    "Quận Hồng Bàng",
    "Quận Ngô Quyền",
    "Quận Lê Chân",
    "Quận Kiến An",
    "Quận Hải An",
    "Huyện An Dương",
    "Huyện An Lão",
    "Huyện Cát Hải",
    "Huyện Kiến Thụy",
  ],
  "Cần Thơ": [
    "Quận Ninh Kiều",
    "Quận Bình Thủy",
    "Quận Cái Răng",
    "Quận Ô Môn",
    "Quận Thốt Nốt",
    "Huyện Cờ Đỏ",
    "Huyện Phong Điền",
    "Huyện Vĩnh Thạnh",
  ],
  "Bình Dương": [
    "Thị xã Thủ Dầu Một",
    "Thị xã Dĩ An",
    "Thị xã Bến Cát",
    "Huyện Tân Uyên",
    "Huyện Bắc Tân Uyên",
    "Huyện Phú Giáo",
    "Huyện Bàu Bàng",
  ],
  "Hải Dương": [
    "Thành phố Hải Dương",
    "Thị xã Chí Linh",
    "Huyện Nam Sách",
    "Huyện Kinh Môn",
    "Huyện Kim Thành",
    "Huyện Thanh Miện",
    "Huyện Cẩm Giàng",
  ],
  "Bình Định": [
    "Thành phố Quy Nhơn",
    "Huyện An Lão",
    "Huyện Hoài Ân",
    "Huyện Phù Cát",
    "Huyện Phù Mỹ",
    "Huyện Tuy Phước",
    "Huyện Vân Canh",
    "Huyện Tây Sơn",
    "Huyện Hoài Nhơn",
    "Huyện Đông Hòa",
    "Huyện Nhơn Hòa",
  ],
};

// Các phường/xã của một số quận/huyện mẫu
export const wards = {
  "Quận Ba Đình": [
    "Phường Phúc Xá",
    "Phường Trúc Bạch",
    "Phường Vĩnh Phúc",
    "Phường Cống Vị",
  ],
  "Quận Hoàn Kiếm": [
    "Phường Hàng Bạc",
    "Phường Hàng Bài",
    "Phường Lý Thái Tổ",
    "Phường Tràng Tiền",
  ],
  "Quận Hai Bà Trưng": [
    "Phường Bách Khoa",
    "Phường Phố Huế",
    "Phường Nguyễn Du",
    "Phường Đồng Tâm",
  ],
  "Quận Tây Hồ": [
    "Phường Phú Thượng",
    "Phường Nhật Tân",
    "Phường Quảng An",
    "Phường Xuân La",
  ],
  "Quận Cầu Giấy": [
    "Phường Dịch Vọng",
    "Phường Mai Dịch",
    "Phường Cầu Giấy",
    "Phường Trung Hòa",
  ],
  "Quận Đống Đa": [
    "Phường Văn Chương",
    "Phường Hàng Bột",
    "Phường Láng Hạ",
    "Phường Ngã Tư Sở",
  ],
  "Quận Hoàng Mai": [
    "Phường Tân Mai",
    "Phường Định Công",
    "Phường Hoàng Liệt",
    "Phường Trần Phú",
  ],
  "Quận Thanh Xuân": [
    "Phường Khương Mai",
    "Phường Thanh Xuân Bắc",
    "Phường Thượng Đình",
    "Phường Kim Giang",
  ],
  "Huyện Ba Vì": [
    "Xã Tản Lĩnh",
    "Xã Minh Quang",
    "Xã Khánh Thượng",
    "Xã Yên Bài",
  ],
  "Huyện Chương Mỹ": [
    "Xã Thượng Vực",
    "Xã Đồng Phú",
    "Xã Tân Tiến",
    "Xã Phú Cường",
  ],
  "Quận 1": [
    "Phường Bến Nghé",
    "Phường Bến Thành",
    "Phường Đa Kao",
    "Phường Nguyễn Thái Bình",
  ],
  "Quận 2": [
    "Phường An Phú",
    "Phường Thạnh Mỹ Lợi",
    "Phường Bình An",
    "Phường Cát Lái",
  ],
  "Quận 3": ["Phường Võ Thị Sáu", "Phường Tân Định", "Phường 6", "Phường 7"],
  "Quận 4": ["Phường 1", "Phường 2", "Phường 3", "Phường 4"],
  "Quận 5": ["Phường 1", "Phường 2", "Phường 3", "Phường 4"],
  "Quận 6": ["Phường 10", "Phường 11", "Phường 12", "Phường 13"],
  "Thành phố Quy Nhơn": [
    "Phường Quang Trung",
    "Phường Trần Quang Diệu",
    "Phường Nguyễn Văn Cừ",
    "Phường Hải Cảng",
    "Phường Bình Định",
    "Phường Nhơn Bình",
    "Phường Ghềnh Ráng",
  ],
  "Huyện Phù Cát": [
    "Xã Cát Khánh",
    "Xã Cát Hanh",
    "Xã Cát Tài",
    "Xã Cát Lâm",
    "Xã Cát Hải",
    "Xã Cát Thành",
    "Xã Cát Sơn",
  ],
};
