stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_PROJECT_NAME: hdnd

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose
  - docker-compose --version

# Build các service từ docker-compose.yml
build_services:
  stage: build
  image: docker:latest
  script:
    - docker-compose -f docker-compose.yml build

# Chạy thử các service (healthcheck)
test_services:
  stage: test
  image: docker:latest
  script:
    - docker-compose -f docker-compose.yml up -d
    - sleep 30
    - docker-compose ps
    # Kiểm tra tình trạng container
    - docker inspect --format='{{json .State.Health}}' hdnd-api-gateway
    - docker inspect --format='{{json .State.Health}}' hdnd-auth-service
    - docker inspect --format='{{json .State.Health}}' hdnd-product-service
    # Dừng và xoá container sau khi test xong
    - docker-compose -f docker-compose.yml down
